version: '3.8'
services:
  frontend:
    build: .
    container_name: student_frontend
    image: student-frontend:1.0
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
      - /app/node_modules