FROM python:3.9

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /backend

RUN apt-get update && apt-get install ffmpeg -y
RUN apt-get install -y libssl-dev build-essential automake pkg-config libtool libffi-dev libgmp-dev libyaml-cpp-dev
RUN apt-get install -y libsecp256k1-dev

COPY ./requirements.txt /backend/

RUN pip3 install -r requirements.txt

COPY ./ /code/

CMD ["python3", "run"]