# Generated by Django 2.2.24 on 2021-06-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20210617_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
