# Generated by Django 2.2.24 on 2021-06-22 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_student_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='timestamp',
        ),
    ]
