# Generated by Django 2.2.24 on 2021-06-23 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20210622_0303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='type',
            new_name='certificate_type',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='university',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='university',
        ),
        migrations.RemoveField(
            model_name='student',
            name='university',
        ),
        migrations.AddField(
            model_name='customuser',
            name='university',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='school.University'),
        ),
        migrations.AddField(
            model_name='professor',
            name='professor_id',
            field=models.CharField(default='', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(default='', max_length=16, null=True),
        ),
    ]
