# Generated by Django 2.2.24 on 2021-06-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20210623_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_type',
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_level',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='grad_year',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='education_form',
            field=models.CharField(default='', max_length=128, null=True),
        ),
    ]
