# Generated by Django 2.2.24 on 2021-06-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20210624_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='avatar',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/uni_pics'),
        ),
    ]
