# Generated by Django 2.2.24 on 2021-06-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_university_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='private_key',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='private_key',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='public_key',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='university',
            name='public_key',
            field=models.TextField(default=''),
        ),
    ]
