# Generated by Django 2.2.24 on 2021-06-29 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20210629_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='avatar',
        ),
    ]
