# Generated by Django 2.2.24 on 2021-06-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_remove_university_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_id',
            field=models.CharField(default='', max_length=7, null=True),
        ),
    ]
