# Generated by Django 2.2.24 on 2021-07-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_subject_subject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='', max_length=60, null=True),
        ),
    ]
