# Generated by Django 2.2.24 on 2021-07-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_auto_20210704_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_id',
            field=models.CharField(default='', max_length=7, unique=True),
        ),
    ]
