# Generated by Django 2.2.24 on 2021-07-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_auto_20210704_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='create_txid',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='update_txid',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='create_txid',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='update_txid',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='txid',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='create_txid',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='update_txid',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='txid',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='txid',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='create_txid',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='update_txid',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='create_txid',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='update_txid',
            field=models.TextField(default='', null=True),
        ),
    ]
