# Generated by Django 2.2.24 on 2021-07-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_auto_20210705_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_id',
            field=models.CharField(default='', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='', max_length=16, unique=True),
        ),
    ]
