# Generated by Django 2.2.24 on 2021-07-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_certificatetransactions_classtransactions_professortransactions_resulttransactions_stafftransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.CharField(default='', max_length=128, null=True),
        ),
    ]
