# Generated by Django 2.2.24 on 2021-07-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_result_result_id'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='result',
        #     name='final_score',
        #     field=models.FloatField(default=''),
        # ),
        # migrations.AlterField(
        #     model_name='result',
        #     name='middle_score',
        #     field=models.FloatField(default=''),
        # ),
    ]
