# Generated by Django 2.2.24 on 2021-07-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_auto_20210715_1243'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='result',
        #     name='final_score',
        #     field=models.FloatField(default='', null=True),
        # ),
        # migrations.AlterField(
        #     model_name='result',
        #     name='middle_score',
        #     field=models.FloatField(default='', null=True),
        # ),
    ]
