# Generated by Django 2.2.24 on 2021-07-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0028_auto_20210715_1244'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='result',
        #     name='final_score',
        #     field=models.FloatField(default=0),
        # ),
        # migrations.AlterField(
        #     model_name='result',
        #     name='middle_score',
        #     field=models.FloatField(default=0),
        # ),
    ]
