# Generated by Django 2.2.24 on 2021-07-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0029_auto_20210715_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='university_id',
            field=models.CharField(default='', max_length=256, unique=True),
        ),
    ]
