# Generated by Django 2.2.24 on 2021-07-18 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0030_university_university_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='create_txid',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='update_txid',
        ),
        migrations.RemoveField(
            model_name='class',
            name='create_txid',
        ),
        migrations.RemoveField(
            model_name='class',
            name='update_txid',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='txid',
        ),
        migrations.RemoveField(
            model_name='result',
            name='create_txid',
        ),
        migrations.RemoveField(
            model_name='result',
            name='update_txid',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='txid',
        ),
        migrations.RemoveField(
            model_name='student',
            name='txid',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='create_txid',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='update_txid',
        ),
        migrations.RemoveField(
            model_name='university',
            name='create_txid',
        ),
        migrations.RemoveField(
            model_name='university',
            name='update_txid',
        ),
    ]
