# Generated by Django 2.2.24 on 2021-07-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0031_auto_20210718_0400'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='certificate',
        #     name='blockchain_id',
        #     field=models.CharField(default='', max_length=128, unique=True),
        # ),
        # migrations.AddField(
        #     model_name='class',
        #     name='blockchain_id',
        #     field=models.CharField(default='', max_length=128, unique=True),
        # ),
        # migrations.AddField(
        #     model_name='professor',
        #     name='blockchain_id',
        #     field=models.CharField(default='', max_length=128, unique=True),
        # ),
        # migrations.AddField(
        #     model_name='result',
        #     name='blockchain_id',
        #     field=models.CharField(default='', max_length=128, unique=True),
        # ),
        # migrations.AddField(
        #     model_name='staff',
        #     name='blockchain_id',
        #     field=models.CharField(default='', max_length=128, unique=True),
        # ),
        # migrations.AddField(
        #     model_name='student',
        #     name='blockchain_id',
        #     field=models.CharField(default='', max_length=128, unique=True),
        # ),
        # migrations.AddField(
        #     model_name='subject',
        #     name='blockchain_id',
        #     field=models.CharField(default='', max_length=128, unique=True),
        # ),
    ]
