# Generated by Django 2.2.24 on 2021-07-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0032_auto_20210720_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='blockchain_key',
            field=models.CharField(default='', max_length=128, null=True),
        ),
    ]
