# Generated by Django 2.2.24 on 2021-07-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0033_student_blockchain_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='blockchain_key',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='blockchain_key',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='blockchain_key',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='blockchain_key',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='blockchain_key',
            field=models.CharField(default='', max_length=128, null=True),
        ),
    ]
