export const GET_FT_TOKENS = 'GET_FT_TOKENS'
export const GET_FT_TOKENS_SUCCESSFUL = 'GET_FT_TOKENS_SUCCESSFUL'
export const GET_NFT_TOKENS = 'GET_NFT_TOKENS'
export const GET_NFT_TOKENS_SUCCESSFUL = 'GET_NFT_TOKENS_SUCCESSFUL'
export const DISPLAY_TOKEN = "DISPLAY_TOKEN"

export const CREATE_TOKENS = 'CREATE_TOKENS'