stages:
  - build

build:
  stage: build
  image: docker:latest
  only:
    - "dev"
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: "overlay"
  retry: 2
  before_script:
    - apk add --no-cache curl
    - docker version
    - "docker info"
    - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
  script:
    - "docker image pull ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest || true"
    - "docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest --cache-from ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest ."
    - "docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest"
  after_script:
    - "docker logout ${CI_REGISTRY}"
