apiVersion: v1
kind: PersistentVolume
metadata:
  name: v-storage-pv
spec:
  storageClassName: nfs-server
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "127.0.0.1"
    path: "/var/nfs/v-storage"