version: '3.8'
services:
  frontend:
    build: .
    container_name: school_frontend
    image: school-frontend:1.0
    ports:
      - "3030:3003"
    volumes:
      - ./:/app
      - /app/node_modules