apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-service
  template:
    metadata:
      labels:
        app: driver-service
    spec:
      volumes:
      - name: fabric-files
        persistentVolumeClaim:
          claimName: fabric-pvc

      containers:
      - name: driver-service
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        image: m4nhb4nhq/fabric-driver:1.2
        command: ["bash", "-c", "cd fabric_appservice && python3 main.py"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /fabric_appservice/projects
          name: fabric-files
      
      imagePullSecrets:
      - name: regcred
