apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-worker
  template:
    metadata:
      labels:
        app: driver-worker
    spec:
      volumes:
      - name: fabric-files
        persistentVolumeClaim:
          claimName: fabric-pvc

      containers:
      - name: driver-worker
        image: m4nhb4nhq/fabric-driver:1.2
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        command: ["make", "dev"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /fabric_appservice/projects
          name: fabric-files
      
      imagePullSecrets:
      - name: regcred
