# Generated by Django 3.2.8 on 2021-10-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FTContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='')),
                ('token_standard', models.CharField(choices=[('ERC-20', 'Erc 20'), ('ERC-721', 'Erc 721'), ('ERC-777', 'Erc 777'), ('ERC-1155', 'Erc 1155')], max_length=16)),
                ('token_name', models.CharField(max_length=64)),
                ('token_symbol', models.CharField(max_length=8)),
                ('token_icon', models.FileField(blank=True, null=True, upload_to='')),
                ('chain_id', models.PositiveIntegerField()),
                ('user_id', models.CharField(max_length=64)),
                ('decimal', models.PositiveSmallIntegerField(default=18)),
                ('initial_supply', models.PositiveBigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NFTContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='')),
                ('token_standard', models.CharField(choices=[('ERC-20', 'Erc 20'), ('ERC-721', 'Erc 721'), ('ERC-777', 'Erc 777'), ('ERC-1155', 'Erc 1155')], max_length=16)),
                ('token_name', models.CharField(max_length=64)),
                ('token_symbol', models.CharField(max_length=8)),
                ('token_icon', models.FileField(blank=True, null=True, upload_to='')),
                ('chain_id', models.PositiveIntegerField()),
                ('user_id', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
