# Generated by Django 3.2.8 on 2021-10-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftcontract',
            name='chain_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ftcontract',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts'),
        ),
        migrations.AlterField(
            model_name='nftcontract',
            name='chain_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nftcontract',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts'),
        ),
    ]
