# Generated by Django 3.2.8 on 2021-10-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211024_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftcontract',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nftcontract',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
