# Generated by Django 3.2.8 on 2021-10-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211024_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftcontract',
            name='initial_supply',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
