# Generated by Django 3.2.8 on 2021-10-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211024_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftcontract',
            name='abi',
            field=models.FileField(blank=True, null=True, upload_to='interfaces'),
        ),
        migrations.AddField(
            model_name='ftcontract',
            name='compiled_code',
            field=models.FileField(blank=True, null=True, upload_to='bin'),
        ),
        migrations.AddField(
            model_name='nftcontract',
            name='abi',
            field=models.FileField(blank=True, null=True, upload_to='interfaces'),
        ),
        migrations.AddField(
            model_name='nftcontract',
            name='compiled_code',
            field=models.FileField(blank=True, null=True, upload_to='bin'),
        ),
    ]
