# Generated by Django 3.2.8 on 2021-10-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211026_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftcontract',
            name='abi',
            field=models.FileField(blank=True, null=True, upload_to='abi'),
        ),
        migrations.AlterField(
            model_name='nftcontract',
            name='abi',
            field=models.FileField(blank=True, null=True, upload_to='abi'),
        ),
    ]
