# Generated by Django 3.2.8 on 2021-10-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211027_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftcontract',
            name='address',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='nftcontract',
            name='address',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
