# Generated by Django 3.2.8 on 2021-11-29 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_ftcontract_mintable'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedFTContracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_ft_contracts', to='api.ftcontract')),
                ('to_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_ft_contracts', to='api.ftcontract')),
            ],
        ),
    ]
