# Generated by Django 3.2.8 on 2021-12-10 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20211130_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeSmartContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts')),
                ('compiled_code', models.FileField(blank=True, null=True, upload_to='bin')),
                ('abi', models.FileField(blank=True, null=True, upload_to='abi')),
                ('address', models.CharField(blank=True, max_length=64, null=True)),
                ('network', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.network')),
            ],
        ),
    ]
