# Generated by Django 3.2.8 on 2021-12-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_fabricftcontract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricftcontract',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Fail', 'Fail'), ('Success', 'Success')], default='Pending', max_length=16),
        ),
    ]
