# Generated by Django 3.2.8 on 2022-02-19 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20220122_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftcontract',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.network'),
        ),
        migrations.AlterField(
            model_name='ftcontract',
            name='user_defined_network',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='nftcontract',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.network'),
        ),
        migrations.AlterField(
            model_name='nftcontract',
            name='user_defined_network',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
