# Generated by Django 3.2.8 on 2022-03-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20220219_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='url',
            field=models.URLField(default='', max_length=256),
        ),
    ]
