# Generated by Django 3.2.8 on 2022-04-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_network_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='supported',
            field=models.BooleanField(default=True),
        ),
    ]
