# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/university.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/university.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19protobuf/university.proto\"\xe3\x02\n\nUniversity\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x19\n\x11\x61tt_university_id\x18\x02 \x01(\t\x12\x1b\n\x13\x61tt_university_name\x18\x03 \x01(\t\x12\x11\n\tatt_email\x18\x04 \x01(\t\x12\x11\n\tatt_phone\x18\x05 \x01(\t\x12\x13\n\x0b\x61tt_address\x18\x06 \x01(\t\x12\x12\n\natt_status\x18\x07 \x01(\t\x12\x16\n\x0e\x61tt_public_key\x18\x08 \x01(\t\x12!\n\x19\x66or_certificate_certi_ids\x18\t \x03(\t\x12\x1b\n\x13\x66or_staff_staff_ids\x18\n \x03(\t\x12!\n\x19\x66or_professor_profess_ids\x18\x0b \x03(\t\x12\x1f\n\x17\x66or_student_student_ids\x18\x0c \x03(\t\x12\x1f\n\x17\x66or_subject_subject_ids\x18\r \x03(\t\"3\n\x13UniversityContainer\x12\x1c\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x0b.Universityb\x06proto3')
)




_UNIVERSITY = _descriptor.Descriptor(
  name='University',
  full_name='University',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='University.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='att_university_id', full_name='University.att_university_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='att_university_name', full_name='University.att_university_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='att_email', full_name='University.att_email', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='att_phone', full_name='University.att_phone', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='att_address', full_name='University.att_address', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='att_status', full_name='University.att_status', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='att_public_key', full_name='University.att_public_key', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='for_certificate_certi_ids', full_name='University.for_certificate_certi_ids', index=8,
      number=9, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='for_staff_staff_ids', full_name='University.for_staff_staff_ids', index=9,
      number=10, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='for_professor_profess_ids', full_name='University.for_professor_profess_ids', index=10,
      number=11, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='for_student_student_ids', full_name='University.for_student_student_ids', index=11,
      number=12, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='for_subject_subject_ids', full_name='University.for_subject_subject_ids', index=12,
      number=13, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=385,
)


_UNIVERSITYCONTAINER = _descriptor.Descriptor(
  name='UniversityContainer',
  full_name='UniversityContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='UniversityContainer.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=438,
)

_UNIVERSITYCONTAINER.fields_by_name['entries'].message_type = _UNIVERSITY
DESCRIPTOR.message_types_by_name['University'] = _UNIVERSITY
DESCRIPTOR.message_types_by_name['UniversityContainer'] = _UNIVERSITYCONTAINER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

University = _reflection.GeneratedProtocolMessageType('University', (_message.Message,), {
  'DESCRIPTOR' : _UNIVERSITY,
  '__module__' : 'protobuf.university_pb2'
  # @@protoc_insertion_point(class_scope:University)
  })
_sym_db.RegisterMessage(University)

UniversityContainer = _reflection.GeneratedProtocolMessageType('UniversityContainer', (_message.Message,), {
  'DESCRIPTOR' : _UNIVERSITYCONTAINER,
  '__module__' : 'protobuf.university_pb2'
  # @@protoc_insertion_point(class_scope:UniversityContainer)
  })
_sym_db.RegisterMessage(UniversityContainer)


# @@protoc_insertion_point(module_scope)
