name: flutter_base
description: Real Agent

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.7.2+172

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  ###########B-Agri###########
  flutter_slidable: ^1.2.0

  ############################
  cupertino_icons: ^1.0.3
  tiengviet: ^0.5.0
  #bloc
  flutter_bloc: ^7.3.0
  get: ^4.3.8
  #router
  fluro: ^2.0.3
  #Cache image
  cached_network_image: ^3.1.0
  flutter_cache_manager: ^3.1.2
  #Photo view
  photo_view: ^0.13.0
  #Image picker
  image_picker: ^0.8.4+2
  #Permission
  permission_handler: ^8.2.2
  #Shimmer
  shimmer: ^2.0.0
  # Share
  share: ^2.0.4
  #Equatable
  equatable: ^2.0.3
  #Retrofit
  retrofit: ^2.0.1
  dio: ^4.0.0
  #Json
  json_annotation: ^4.3.0
  #Shared_preferences
  shared_preferences: ^2.0.8
  #Hive
  #hive: ^1.4.4+1
  #hive_flutter: ^0.3.1
  #secure storage
  flutter_secure_storage: ^4.2.1
  #Reactive
  rxdart: ^0.27.2
  #Connectivity
  connectivity: ^3.0.6
  #flushbar
  another_flushbar: ^1.10.24
  overlay_support: ^1.2.1
  intl_utils: ^2.4.1
  #flutter_picker
  #  flutter_picker: ^1.1.5

  pin_code_fields: ^7.3.0
  scroll_to_index: ^2.1.0

  #Dotted border
  #  dotted_border: ^1.0.7
  #Number format
  intl: ^0.17.0

  #Firebase
  firebase_analytics: ^8.3.3
  firebase_messaging: ^10.0.8
  firebase_crashlytics: ^2.2.3
  firebase_dynamic_links: ^2.0.10

  # Date time picker
  flutter_datetime_picker: ^1.5.1
  scrollable_positioned_list: ^0.2.0-nullsafety.0

  expandable: ^5.0.1
  syncfusion_flutter_pdfviewer: ^19.3.44-beta
  #map
  google_maps_flutter: ^2.0.11

  #uid
  uuid: ^3.0.5
  # file picker
  #  file_picker: ^1.13.3
  flutter_document_picker: ^5.0.1-nullsafety.0
  # multi image picker
  multi_image_picker: ^4.8.01

  #upgrader
  upgrader: ^3.6.0
  #scan qrcode
  qr_flutter: ^4.0.0

  #webView
  flutter_inappwebview: ^5.3.2

  smooth_page_indicator: ^1.0.0+2

  #package lib
  package_info: ^2.0.2

  qr_code_scanner: ^0.5.2
  wakelock: ^0.5.6

  #url_launcher
  url_launcher: ^6.0.12
  #dotted_line
  dotted_line: ^3.0.1
  #currency
  currency_text_input_formatter: ^2.1.4
  # take a screenshot
  screenshot: ^1.2.3
  # image gallery saver
  image_gallery_saver: ^1.7.1
  dotted_decoration: ^2.0.0

  build_resolvers: ^2.0.4
  collection: ^1.15.0-nullsafety.4
  firebase_core: ^1.7.0
  flutter_linkify: ^5.0.2

  # get location
  geolocator: ^7.0.3
  flutter_html: ^2.2.0
  location_web: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  retrofit_generator: ^2.0.1+2
  json_serializable: ^6.0.0

dependency_overrides:


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # Json file
    - assets/area/
    - assets/list_bank/
    - assets/images/
    # Common images

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto-ThinItalic.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-LightItalic.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-BoldItalic.ttf
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-BlackItalic.ttf
flutter_intl:
  enabled: true
