export const OPEN_CUSTOM_ALERT = "OPEN_CUSTOM_ALERT";
export const OPEN_SUCCESS_ALERT = "OPEN_SUCCESS_ALERT";
export const OPEN_ERROR_ALERT = "OPEN_ERROR_ALERT";
export const OPEN_WARNING_ALERT = "OPEN_WARNING_ALERT";
export const OPEN_INFO_ALERT = "OPEN_INFO_ALERT";
export const CLOSE_ALERT = "CLOSE_ALERT";
