apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sawtooth-service-pvc
spec:
  storageClassName: nfs-server
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: sawtooth-service-files
