apiVersion: v1
kind: PersistentVolume
metadata:
  name: sawtooth-service-pv
  labels:
    name: sawtooth-service-files
spec:
  storageClassName: nfs-server
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "localhost"
    path: "/var/nfs/sawtooth-service"
  